#!/bin/sh
# This wrapper exists mostly for testing / development.
# Install via pip for normal use.

SOURCE=$(readlink -f ${BASH_SOURCE:-$0})
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
export PYTHONPATH=$DIR/src:${PYTHONPATH}
exec python3 -u -c 'from dnskeytool.shell import main; main()' "$@"
